# Use alpine for smaller build size
FROM node:18-alpine

WORKDIR /app

# Copy the files to know which node modules to install
COPY notes-frontend/package.json .
COPY notes-frontend/package-lock.json .

# Install npm to build the code into web servable bytecode
RUN npm install

# Copy all the frontend code into the Docker container
COPY notes-frontend .

# Run using npm
CMD ["npm", "start"]