"""initial

Revision ID: 748a3f3b44e6
Revises:
Create Date: 2022-11-28 09:35:29.149259

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "748a3f3b44e6"
down_revision = "a51fd4e3968a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes',
        sa.Column(
            "entities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='[]',
            nullable=True,
            comment="JSON formatted array of entities, each one is a string",
        )),
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'entities')
    # ### end Alembic commands ###
