"""initial

Revision ID: a51fd4e3968a
Revises:
Create Date: 2022-11-23 12:27:25.149259

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a51fd4e3968a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notes",
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("NOW()::timestamp"),
            nullable=False,
        ),
        sa.Column(
            "modified",
            sa.DateTime(),
            server_default=sa.text("NOW()::timestamp"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="id of the note",
        ),
        sa.Column(
            "content", sa.String(), nullable=False, comment="content of the note"
        ),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='["random"]',
            nullable=False,
            comment="JSON formatted array of tags, each one is a string",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notes_created"),
        "notes",
        ["created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notes_modified"),
        "notes",
        ["modified"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notes_modified"), table_name="notes")
    op.drop_index(op.f("ix_notes_created"), table_name="notes")
    op.drop_table("notes")
    # ### end Alembic commands ###
